language: rust
cache: cargo
rust:
  - stable
before_script:
  - rustup component add clippy
script:
  - cargo clippy -- -D warnings
notifications:
  email:
    on_success: change
    on_failure: always
branches:
  only:
    - master
