[package]
name = "kube-rt"
version = "0.1.0"
authors = ["Teo Klestrup Röijezon <teo@nullable.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.4"
kube = "0.33.0"
k8s-openapi = "0.7.1"
derivative = "2.1.1"
serde = "1.0.106"
dashmap = "3.11.1"
smallvec = "1.4.0"
pin-project = "0.4.10"

[dependencies.snafu]
version = "0.6.6"
features = ["futures"]

[dependencies.tokio]
version = "0.2.20"
features = ["time"]

[dev-dependencies]
anyhow = "1.0.28"
kube-derive = "0.33.0"
serde_json = "1.0.52"

[dev-dependencies.k8s-openapi]
version = "0.7.1"
features = ["v1_16"]

[dev-dependencies.tokio]
version = "0.2.20"
features = ["macros"]
