version: 2.1

workflows:
  version: 2
  all_jobs:
    jobs:
      - cargo_test

jobs:
  cargo_test:
    docker:
      - image: circleci/rust:latest
    environment:
      - CARGO_INCREMENTAL: 0
    steps:
      - checkout
      # Cache is based on whether we changed dependencies:
      - run: grep "\[dependencies\]" -A 9000 kube/Cargo.toml > deps_checksum
      - restore_cache:
          keys:
          - cache-{{ checksum "deps_checksum" }}
      - run: cargo build
      - run: cargo test --lib
      - run: cargo test --example crd_api crd_reflector
      - run: cargo test -j4
      - run: cargo test --lib --no-default-features --features=rustls-tls
      - save_cache:
          paths:
            - /usr/local/cargo/registry
            - target/debug/.fingerprint
            - target/debug/build
            - target/debug/deps
          key: cache-{{ checksum "deps_checksum" }}
