[package]
name = "kube-runtime"
version = "0.36.0"
authors = [
  "Teo Klestrup Röijezon <teo@nullable.se>",
  "clux <sszynrae@gmail.com>",
]
edition = "2018"

[dependencies]
futures = "0.3.5"
kube = { path = "../kube", default-features = false }
k8s-openapi = "0.8.0"
derivative = "2.1.1"
serde = "1.0.110"
smallvec = "1.4.0"
pin-project = "0.4.16"
tokio = { version = "0.2.21", features = ["time"] }
snafu = { version = "0.6.8", features = ["futures"] }
dashmap = "4.0.0-rc6"

[features]
default = ["native-tls"]
native-tls = ["kube/native-tls"]
rustls-tls = ["kube/rustls-tls"]

[dev-dependencies.k8s-openapi]
version = "0.8.0"
default-features = false
features = ["v1_18"]
