[package]
name = "kube-derive"
description = "Custom derives for the kube kubernetes client library"
version = "0.34.0"
authors = ["clux <sszynrae@gmail.com>"]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/clux/kube-rs"
readme = "../README.md"

[dependencies]
proc-macro2 = "1.0.18"
quote = "1.0.6"
syn = { version = "1.0.30", features = ["extra-traits"] }
Inflector = "0.11.4"
serde_json = "1.0.53"

[lib]
proc-macro = true
